### ISSUE TITLE
Could not pass event InventoryMoveItemEvent to ShopItemOnly 

### ISSUE THREAD

**Issue by NotAlexNoyle** [bukkitcommons/QuickShopAddon-ShopItemOnly#1]
This plugin causes a crash that loops infinitely and renders my server inoperable

`[20:17:27 ERROR]: Could not pass event InventoryMoveItemEvent to ShopItemOnly v1.1
java.lang.NoSuchMethodError: 'org.maxgamer.quickshop.shop.ShopManager org.maxgamer.quickshop.QuickShop.getShopManager()'
        at cc.bukkit.quickshop.addon.shopitemonly.ShopItemOnly.invMove(ShopItemOnly.java:83) ~[ShopItemOnly-1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor433.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:313) ~[app:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:241) ~[app:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.a(HopperBlockEntity.java:384) ~[app:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:186) ~[app:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:167) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1491) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1443) ~[app:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1066) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:796) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:495) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-19]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by sandtechnology** [comment]
Sorry for no response, it should fixed in 1.2, you can download it here: https://www.spigotmc.org/resources/quickshop-addon-shopitemonly.78669/
